### ISSUE TITLE
Tests fail due to line ending differences.

### ISSUE THREAD

**Issue by grokys** [grokys/Octokit.GraphQL#20]
We need to ignore line ending differences when comparing test result strings. Currently on Windows e.g. `QueryBuilderTests.Field_Aliases` fails because the test was written on I assume a Mac (am I right @StanleyGoldman?) and the expected strings therefore have `\n` line endings whereas the serialized string has `\r\n` line endings.

**Comment by StanleyGoldman** [comment]
I can work that out on a Mac

**Comment by StanleyGoldman** [comment]
Your comment on #16 makes me wonder... I'm working on a PC now, we shouldn't be seeing this error between the two of us.

**Comment by grokys** [comment]
Yeah, it's weird - once I merged #16 to master, the tests started passing?! Not sure what's happening.

**Comment by StanleyGoldman** [comment]
Ah... These two tests were in the wrong branch..
- RepositoryTests.Should_QueryRepositoryOwner_Repositories_OrderBy_Name_Ascending
- RepositoryTests.Should_QueryRepositoryOwner_Repositories_OrderBy_CreatedAt_Descending

**Comment by grokys** [comment]
Fixed.
